/* Auto-generated by generate-uns-measurements.ts. Do not edit by hand. */
export const GeneratedPhysicalMeasurements = {
  /** Brez enote */
  "None": "",
  /** Milimeter */
  "MiliMeter": "mm",
  /** Meter */
  "Meter": "m",
  /** Kilometer */
  "KiloMeter": "km",
  /** Čevlji */
  "Feet": "ft",
  /** Sekunda */
  "Second": "s",
  /** Minuta */
  "Minute": "min",
  /** Ura */
  "Hour": "h",
  /** Dan */
  "Day": "day",
  /** Herc */
  "Hertz": "Hz",
  /** Kubični meter */
  "CubicMeter": "m^3",
  /** Liter */
  "Liter": "l",
  /** Galona */
  "Gallon": "gal",
  /** Funt na kvadratni palec */
  "Psi": "psi",
  /** Pascal */
  "Pascal": "Pa",
  /** Bar */
  "Bar": "bar",
  /** Stopinje Celzija */
  "Celsius": "°C",
  /** Stopinje Fahrenheita */
  "Fahrenheit": "°F",
  /** Kelvin */
  "Kelvin": "K",
  /** Milidžul */
  "Milijoule": "mJ",
  /** Džul */
  "Joule": "J",
  /** Kilodžul */
  "Kilojoule": "kJ",
  /** Megadžul */
  "Megajoule": "MJ",
  /** Gigadžul */
  "Gigajoule": "GJ",
  /** Teradžul */
  "Terajoule": "TJ",
  /** Njuton */
  "Newton": "N",
  /** Bit */
  "Bit": "bit",
  /** Bajt */
  "Byte": "byte",
  /** Bajti */
  "B": "B",
  /** Milimeter na sekundo */
  "MilimeterPerSecond": "mm/s",
  /** Meter na sekundo */
  "MeterPerSecond": "m/s",
  /** Meter na minuto */
  "MeterPerMinute": "m/min",
  /** Centimeter na sekundo */
  "CentiMeterPerSecond": "cm/s",
  /** Meter na uro */
  "MeterPerHour": "m/h",
  /** Kilometer na uro */
  "KilometerPerHour": "km/h",
  /** Obratov na minuto */
  "RevolutionsPerMinute": "rpm",
  /** Odstotek */
  "Percent": "percent",
  /** Delci na milijon */
  "PartsPerMillion": "ppm",
  /** Delci na milijardo */
  "PartsPerBillion": "ppb",
  /** Delci na trilijon */
  "PartsPerTrillion": "ppt",
  /** Decibel */
  "Decibel": "dB",
  /** Stopinja */
  "Degree": "°",
  /** Radian */
  "Radian": "rad",
  /** Miligram */
  "Miligram": "mg",
  /** Gram */
  "Gram": "g",
  /** Kilogram */
  "Kilogram": "kg",
  /** Tona */
  "MetricTon": "t",
  /** Milivolt */
  "MiliVolt": "mV",
  /** Volt */
  "Volt": "V",
  /** Kilovolt */
  "KiloVolt": "kV",
  /** Megavolt */
  "MegaVolt": "MV",
  /** Miliamper */
  "MiliAmpere": "mA",
  /** Amper */
  "Ampere": "A",
  /** Kiloamper */
  "KiloAmpere": "kA",
  /** Megaamper */
  "MegaAmpere": "MA",
  /** Miliwatt */
  "MiliWatt": "mW",
  /** Watt */
  "Watt": "W",
  /** Kilowatt */
  "KiloWatt": "kW",
  /** Megawatt */
  "MegaWatt": "MW",
  /** Miliwattna ura */
  "MiliWattHour": "mWh",
  /** Wattna ura */
  "WattHour": "Wh",
  /** Kilowattna ura */
  "KiloWattHour": "kWh",
  /** Megawattna ura */
  "MegaWattHour": "MWh",
  /** Milivolt-amper */
  "MiliVoltAmpere": "mVA",
  /** Volt-amper */
  "VoltAmpere": "VA",
  /** Kilovolt-amper */
  "KiloVoltAmpere": "kVA",
  /** Megavolt-amper */
  "MegaVoltAmpere": "MVA",
  /** Milivolt-reaktivni amper */
  "MiliVoltAmpereReactive": "mVAR",
  /** Volt-reaktivni amper */
  "VoltAmpereReactive": "VAR",
  /** Kilovolt-reaktivni amper */
  "KiloVoltAmpereReactive": "kVAR",
  /** Megavolt-reaktivni amper */
  "MegaVoltAmpereReactive": "MVAR",
  /** Kubični meter na uro */
  "CubicMeterPerHour": "m^3/h",
  /** Kubični meter na sekundo */
  "CubicMeterPerSecond": "m^3/s",
  /** Megagram na uro */
  "MegaGramPerHour": "Mg/h",
  /** Tona na uro */
  "MetricTonPerHour": "t/h",
} as const;

export const GeneratedDataSizeMeasurements = {
  /** Bit */
  "Bit": "bit",
  /** Bajt */
  "Byte": "B",
  /** Kilobajt */
  "KiloByte": "kB",
  /** Megabajt */
  "MegaByte": "MB",
  /** Gigabajt */
  "GigaByte": "GB",
  /** Terabajt */
  "TeraByte": "TB",
  /** Petabajt */
  "PetaByte": "PB",
  /** Eksabajt */
  "ExaByte": "EB",
  /** Zetabajt */
  "ZettaByte": "ZB",
  /** Jotabajt */
  "YottaByte": "YB",
} as const;

export const GeneratedCounterMeasurements = {
  /** Kilo */
  "Kilo": "k",
  /** Mega */
  "Mega": "M",
  /** Giga */
  "Giga": "G",
} as const;

export type GeneratedPhysicalMeasurement = typeof GeneratedPhysicalMeasurements[keyof typeof GeneratedPhysicalMeasurements];
export type GeneratedDataSizeMeasurement = typeof GeneratedDataSizeMeasurements[keyof typeof GeneratedDataSizeMeasurements];
export type GeneratedCounterMeasurement = typeof GeneratedCounterMeasurements[keyof typeof GeneratedCounterMeasurements];
export type GeneratedMeasurementUnit = GeneratedPhysicalMeasurement | GeneratedDataSizeMeasurement | GeneratedCounterMeasurement | (string & {});
