/* Auto-generated by generate-uns-dictionary.ts. Do not edit by hand. */
export const GeneratedObjectTypes = {
  /** Fizična oprema (stroji, peči, senzorji). Uporablja se za spremljanje stanja, meritev in dogodkov. */
  "equipment": "equipment",
  /** Materialne enote (loti, serije, surovine, polizdelki). Za sledljivost, količine in premike. */
  "material": "material",
  /** Osebje (operaterji, nadzorniki, tehnologi). Za prisotnost, naloge in status. */
  "personnel": "personnel",
  /** Posamezen korak v procesu (npr. valjanje, hlajenje, analiza). Za faze ali aktivnosti procesa. */
  "process-segment": "process-segment",
  /** Definicija izdelka, recepture, tehnični opisi. Za metapodatke izdelka in revizije. */
  "product-definition": "product-definition",
  /** Kazalniki kakovosti izdelka (odstopanja, ocene, rezultati meritev). */
  "product-quality": "product-quality",
  /** Definicija nalog ali delovnih tokov. Za planirane operacije in navodila. */
  "work-definition": "work-definition",
  /** Status kateregakoli vira (material, osebje, oprema). Za razpoložljivost, okvare, izrabo. */
  "resource-status": "resource-status",
  /** Energija (elektrika, para, plin). */
  "energy-resource": "energy-resource",
  /** Utility viri (voda, zrak, dušik, stisnjeni plini). */
  "utility-resource": "utility-resource",
  /** Tekočine in plini, ki niso energenti. */
  "fluid-resource": "fluid-resource",
  /** Maziva, olja, čistila, ki se porabijo in niso del izdelka. */
  "consumable-resource": "consumable-resource",
} as const;

export const GeneratedObjectTypeDescriptions: Record<keyof typeof GeneratedObjectTypes, string> = {
  "equipment": "Fizična oprema (stroji, peči, senzorji). Uporablja se za spremljanje stanja, meritev in dogodkov.",
  "material": "Materialne enote (loti, serije, surovine, polizdelki). Za sledljivost, količine in premike.",
  "personnel": "Osebje (operaterji, nadzorniki, tehnologi). Za prisotnost, naloge in status.",
  "process-segment": "Posamezen korak v procesu (npr. valjanje, hlajenje, analiza). Za faze ali aktivnosti procesa.",
  "product-definition": "Definicija izdelka, recepture, tehnični opisi. Za metapodatke izdelka in revizije.",
  "product-quality": "Kazalniki kakovosti izdelka (odstopanja, ocene, rezultati meritev).",
  "work-definition": "Definicija nalog ali delovnih tokov. Za planirane operacije in navodila.",
  "resource-status": "Status kateregakoli vira (material, osebje, oprema). Za razpoložljivost, okvare, izrabo.",
  "energy-resource": "Energija (elektrika, para, plin).",
  "utility-resource": "Utility viri (voda, zrak, dušik, stisnjeni plini).",
  "fluid-resource": "Tekočine in plini, ki niso energenti.",
  "consumable-resource": "Maziva, olja, čistila, ki se porabijo in niso del izdelka.",
};

export type GeneratedObjectTypeName = keyof typeof GeneratedObjectTypes;

export function getGeneratedObjectTypeDescription(name: string): string | undefined {
  return (GeneratedObjectTypeDescriptions as Record<string, string | undefined>)[name];
}

export const GeneratedAttributesByType = {
  "equipment": {
    "status": "status",
    "temperature": "temperature",
    "vibration": "vibration",
    "operating-hours": "operating-hours",
    "fault-code": "fault-code",
    "speed": "speed",
    "energy-consumption": "energy-consumption",
  },
  "material": {
    "lot-id": "lot-id",
    "batch-number": "batch-number",
    "material-type": "material-type",
    "quantity": "quantity",
    "location": "location",
    "status": "status",
  },
  "personnel": {
    "presence": "presence",
    "task-id": "task-id",
    "role": "role",
    "status": "status",
  },
  "process-segment": {
    "start-time": "start-time",
    "end-time": "end-time",
    "duration": "duration",
    "status": "status",
    "output-quantity": "output-quantity",
  },
  "product-definition": {
    "product-code": "product-code",
    "revision": "revision",
    "specification": "specification",
    "target-parameters": "target-parameters",
    "material-composition": "material-composition",
    "version-history": "version-history",
  },
  "product-quality": {
    "inspection-result": "inspection-result",
    "deviation": "deviation",
    "pass-fail": "pass-fail",
    "surface-defect": "surface-defect",
    "hardness": "hardness",
    "tensile-strength": "tensile-strength",
  },
  "work-definition": {
    "work-order-id": "work-order-id",
    "task-list": "task-list",
    "planned-start": "planned-start",
    "planned-end": "planned-end",
    "assigned-to": "assigned-to",
    "instruction-url": "instruction-url",
  },
  "resource-status": {
    "availability": "availability",
    "utilization": "utilization",
    "downtime": "downtime",
    "status": "status",
    "maintenance-status": "maintenance-status",
  },
  "energy-resource": {
    "power": "power",
    "energy": "energy",
    "voltage": "voltage",
    "current": "current",
    "frequency": "frequency",
    "cost": "cost",
  },
  "utility-resource": {
    "pressure": "pressure",
    "flow": "flow",
    "consumption": "consumption",
    "status": "status",
    "alarm": "alarm",
  },
  "fluid-resource": {
    "flow": "flow",
    "pressure": "pressure",
    "temperature": "temperature",
    "total-flow": "total-flow",
    "conductivity": "conductivity",
    "ph": "ph",
  },
  "consumable-resource": {
    "level": "level",
    "consumption-rate": "consumption-rate",
    "refill-required": "refill-required",
    "last-refill": "last-refill",
    "status": "status",
  }
} as const;

export const GeneratedAttributes = {
  /** Trenutno stanje vira ali opreme. */
  "status": "status",
  /** Temperatura vira/opreme. */
  "temperature": "temperature",
  /** Merjena vibracija. */
  "vibration": "vibration",
  /** Število obratovalnih ur. */
  "operating-hours": "operating-hours",
  /** Koda napake. */
  "fault-code": "fault-code",
  /** Hitrost delovanja. */
  "speed": "speed",
  /** Poraba energije. */
  "energy-consumption": "energy-consumption",
  /** Identifikator lota. */
  "lot-id": "lot-id",
  /** Številka serije (batch). */
  "batch-number": "batch-number",
  /** Tip materiala. */
  "material-type": "material-type",
  /** Količina materiala. */
  "quantity": "quantity",
  /** Lokacija materiala ali opreme. */
  "location": "location",
  /** Prisotnost osebja. */
  "presence": "presence",
  /** Identifikator naloge. */
  "task-id": "task-id",
  /** Vloga osebja. */
  "role": "role",
  /** Nivo pooblastil. */
  "authorization-level": "authorization-level",
  /** Čas začetka. */
  "start-time": "start-time",
  /** Čas zaključka. */
  "end-time": "end-time",
  /** Trajanje faze ali naloge. */
  "duration": "duration",
  /** Izhodna količina. */
  "output-quantity": "output-quantity",
  /** Identifikator operaterja. */
  "operator-id": "operator-id",
  /** Koda izdelka. */
  "product-code": "product-code",
  /** Revizija izdelka. */
  "revision": "revision",
  /** Tehnične specifikacije. */
  "specification": "specification",
  /** Ciljni parametri izdelka ali procesa. */
  "target-parameters": "target-parameters",
  /** Sestava materiala. */
  "material-composition": "material-composition",
  /** Zgodovina verzij. */
  "version-history": "version-history",
  /** Rezultat pregleda. */
  "inspection-result": "inspection-result",
  /** Odstopanje od specifikacije. */
  "deviation": "deviation",
  /** Uspešno/neuspešno (pass/fail). */
  "pass-fail": "pass-fail",
  /** Površinska napaka. */
  "surface-defect": "surface-defect",
  /** Trdota materiala. */
  "hardness": "hardness",
  /** Natezna trdnost. */
  "tensile-strength": "tensile-strength",
  /** Identifikator delovnega naloga. */
  "work-order-id": "work-order-id",
  /** Seznam nalog. */
  "task-list": "task-list",
  /** Planirani začetek. */
  "planned-start": "planned-start",
  /** Planirani zaključek. */
  "planned-end": "planned-end",
  /** Dodeljeno osebi ali ekipi. */
  "assigned-to": "assigned-to",
  /** Povezava do navodil. */
  "instruction-url": "instruction-url",
  /** Razpoložljivost vira. */
  "availability": "availability",
  /** Izraba vira. */
  "utilization": "utilization",
  /** Zastoj/izpad. */
  "downtime": "downtime",
  /** Stanje vzdrževanja. */
  "maintenance-status": "maintenance-status",
  /** Moč. */
  "power": "power",
  /** Energija. */
  "energy": "energy",
  /** Napetost. */
  "voltage": "voltage",
  /** Tok. */
  "current": "current",
  /** Frekvenca. */
  "frequency": "frequency",
  /** Strošek. */
  "cost": "cost",
  /** Tlak. */
  "pressure": "pressure",
  /** Pretok. */
  "flow": "flow",
  /** Poraba. */
  "consumption": "consumption",
  /** Alarmni signal. */
  "alarm": "alarm",
  /** Skupni pretok. */
  "total-flow": "total-flow",
  /** Prevodnost. */
  "conductivity": "conductivity",
  /** pH vrednost. */
  "ph": "ph",
  /** Nivo zaloge ali rezervoarja. */
  "level": "level",
  /** Hitrost porabe. */
  "consumption-rate": "consumption-rate",
  /** Potrebno dolivanje/dopolnitev. */
  "refill-required": "refill-required",
  /** Zadnje polnjenje. */
  "last-refill": "last-refill",
} as const;

export const GeneratedAttributeDescriptions: Record<keyof typeof GeneratedAttributes, string> = {
  "status": "Trenutno stanje vira ali opreme.",
  "temperature": "Temperatura vira/opreme.",
  "vibration": "Merjena vibracija.",
  "operating-hours": "Število obratovalnih ur.",
  "fault-code": "Koda napake.",
  "speed": "Hitrost delovanja.",
  "energy-consumption": "Poraba energije.",
  "lot-id": "Identifikator lota.",
  "batch-number": "Številka serije (batch).",
  "material-type": "Tip materiala.",
  "quantity": "Količina materiala.",
  "location": "Lokacija materiala ali opreme.",
  "presence": "Prisotnost osebja.",
  "task-id": "Identifikator naloge.",
  "role": "Vloga osebja.",
  "authorization-level": "Nivo pooblastil.",
  "start-time": "Čas začetka.",
  "end-time": "Čas zaključka.",
  "duration": "Trajanje faze ali naloge.",
  "output-quantity": "Izhodna količina.",
  "operator-id": "Identifikator operaterja.",
  "product-code": "Koda izdelka.",
  "revision": "Revizija izdelka.",
  "specification": "Tehnične specifikacije.",
  "target-parameters": "Ciljni parametri izdelka ali procesa.",
  "material-composition": "Sestava materiala.",
  "version-history": "Zgodovina verzij.",
  "inspection-result": "Rezultat pregleda.",
  "deviation": "Odstopanje od specifikacije.",
  "pass-fail": "Uspešno/neuspešno (pass/fail).",
  "surface-defect": "Površinska napaka.",
  "hardness": "Trdota materiala.",
  "tensile-strength": "Natezna trdnost.",
  "work-order-id": "Identifikator delovnega naloga.",
  "task-list": "Seznam nalog.",
  "planned-start": "Planirani začetek.",
  "planned-end": "Planirani zaključek.",
  "assigned-to": "Dodeljeno osebi ali ekipi.",
  "instruction-url": "Povezava do navodil.",
  "availability": "Razpoložljivost vira.",
  "utilization": "Izraba vira.",
  "downtime": "Zastoj/izpad.",
  "maintenance-status": "Stanje vzdrževanja.",
  "power": "Moč.",
  "energy": "Energija.",
  "voltage": "Napetost.",
  "current": "Tok.",
  "frequency": "Frekvenca.",
  "cost": "Strošek.",
  "pressure": "Tlak.",
  "flow": "Pretok.",
  "consumption": "Poraba.",
  "alarm": "Alarmni signal.",
  "total-flow": "Skupni pretok.",
  "conductivity": "Prevodnost.",
  "ph": "pH vrednost.",
  "level": "Nivo zaloge ali rezervoarja.",
  "consumption-rate": "Hitrost porabe.",
  "refill-required": "Potrebno dolivanje/dopolnitev.",
  "last-refill": "Zadnje polnjenje.",
};

export type GeneratedAttributeName = keyof typeof GeneratedAttributes;

export function getGeneratedAttributeDescription(name: string): string | undefined {
  return (GeneratedAttributeDescriptions as Record<string, string | undefined>)[name];
}

export type GeneratedAttributesFor<T extends keyof typeof GeneratedAttributesByType> = keyof typeof GeneratedAttributesByType[T];
